host: data.silknow.org # required
port: 8871 # default 8889
admin: troncy@eurecom.fr # default you@example.org
apache_conf: source.conf # if you want to customise the apache conf
list: # default []
  - vocabulary
  - object
  - document
  - image
  - organization
  - event
  - assestment
  - production
  - actor
  - person
  - place
  - modification
  - inscription
  - garin
  - collection
  - category
  - graph
  - has_type_P2
  - timespan
  - assessment
